name: Docker CI/CD

"on":
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest


steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Deploy to EC2
    uses: appleboy/ssh-action@master

    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USERNAME }}
      key: ${{ secrets.EC2_SSH_KEY }}

      script: |
        cd ~/node-docker-app
        git pull origin main
        sudo docker stop docker-node-app || true
        sudo docker rm docker-node-app || true
        sudo docker build -t my-node-app .
        sudo docker run -d -p 3000:3000 --name docker-node-app my-node-app

