name: Docker CI/CD

on:
push:
branches: ["main"]

jobs:
build:
runs-on: ubuntu-latest


steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Build Docker image
    run: docker build -t my-node-app .

  - name: Run container (test)
    run: docker run -d -p 3000:3000 my-node-app

